version: '3.8'

services:
  postgres-reactive:
    container_name: postgres-reactive
    image: postgres:16-alpine
    ports:
      - "7432:5432"
    environment:
      - "POSTGRES_DB=product"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=strongpassword"
    restart: always
    networks:
      - reactive-network

  product:
    container_name: product
    build: product-service
    depends_on:
      - postgres-reactive
    ports:
      - "7071:7071"
      - "7001:7001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - R2DBC_URL=r2dbc:postgresql://postgres-reactive:5432/product
      - JDBC_URL=jdbc:postgresql://postgres-reactive:5432/product
      - DB_USERNAME=postgres
      - DB_PASSWORD=strongpassword
    networks:
      - reactive-network

  api-gateway:
    container_name: api-gateway
    build: armeria-api-gateway
    depends_on:
      - product
    ports:
      - "5555:5555"
    environment:
      - PRODUCT_SERVICE_GRPC_HOST=product
      - PRODUCT_SERVICE_GRPC_PORT=7071
    networks:
      - reactive-network

networks:
  reactive-network:
    driver: bridge