global:
  scrape_interval: 10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: 'gradle-timezones'
    scheme: http
    metrics_path: '/metrics'
    authorization:
      type: "apikey"
      credentials: "GradleInterviewArmeria!!2024"
    static_configs:
      - targets:
          - 'host.docker.internal:5555'
