server:
  port: 7001
spring:
  application:
    name: product-service
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:7432/product}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:strongpassword}
    pool:
      max-size: 40
  flyway:
    url: ${JDBC_URL:jdbc:postgresql://localhost:7432/product}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:strongpassword}
    locations: classpath:db/migration

logging:
  level:
    root: info
    com:
      example: DEBUG
    r2dbc: DEBUG
    sql: TRACE
    web: DEBUG
  group:
    r2dbc: 'org.springframework.r2dbc,org.springframework.data.r2dbc'
