services:
  postgres-finmid:
    image: postgres:16-alpine
    ports:
      - "7432:5432"
    environment:
      - "POSTGRES_DB=finmid"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=strongpassword"
    restart: always

volumes:
    certs:
