global:
  scrape_interval: 10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus-reactive:9090
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: 'armeria-services'
    scheme: http
    metrics_path: '/metrics'
    authorization:
      type: "apikey"
      credentials: "GradleInterviewArmeria!!2024"
    static_configs:
      - targets:
          - 'host.docker.internal:5555'
  - job_name: otel_collector
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - otel-collector-reactive:8888